import { execFileSync } from "node:child_process";
import { rmSync } from "node:fs";
import { resolve } from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { PrismaLibSql } from "@prisma/adapter-libsql";
import { PrismaClient } from "@/generated/prisma/client";
import { ingestAxdb } from "@/lib/ingest";
import {
  bestPaxMsForEntry,
  buildDriverHistory,
  type EntryForHistory,
} from "@/lib/driver-history";

const TEST_DB_PATH = resolve(__dirname, "..", "test-driver-history.db");
const TEST_DB_URL = "file:./test-driver-history.db";

const FIXTURES_DIR = resolve(__dirname, "fixtures");
const SEASON_EVENTS = [
  "season-event-1.axdb",
  "season-event-2.axdb",
  "season-event-3.axdb",
  "season-event-4.axdb",
  "season-event-5.axdb",
];

// M1.17: reuse the existing M1.15 combined-event fixture set (regenerated by
// `pretest` via build-combined-event-season.mjs) to exercise same-date
// session-pair collapsing. See that script's header comment for the full
// scenario/math -- distinct member numbers (CMB-*) from the season fixtures
// above (MES-*), so ingesting both into one DB doesn't cross-contaminate.
const COMBINED_EVENTS = [
  "combined-event-1-opener.axdb",
  "combined-event-2-classic.axdb",
  "combined-event-3a.axdb",
  "combined-event-3b.axdb",
];

let prisma: PrismaClient;
let alexId: number;
let beaId: number;
let camId: number;
let evanId: number;
let quinnId: number;
let raeId: number;
let leoId: number;

beforeAll(async () => {
  rmSync(TEST_DB_PATH, { force: true });
  execFileSync("pnpm", ["exec", "prisma", "migrate", "deploy"], {
    cwd: resolve(__dirname, ".."),
    env: { ...process.env, DATABASE_URL: TEST_DB_URL },
    stdio: "pipe",
  });
  const adapter = new PrismaLibSql({ url: TEST_DB_URL });
  prisma = new PrismaClient({ adapter });

  for (const filename of SEASON_EVENTS) {
    await ingestAxdb(resolve(FIXTURES_DIR, filename), prisma);
  }
  for (const filename of COMBINED_EVENTS) {
    await ingestAxdb(resolve(FIXTURES_DIR, filename), prisma);
  }

  const drivers = await prisma.driver.findMany({
    where: { memberNum: { in: ["MES-001", "MES-002", "MES-003", "MES-005"] } },
  });
  const byMember = new Map(drivers.map((d) => [d.memberNum!, d.id]));
  alexId = byMember.get("MES-001")!;
  beaId = byMember.get("MES-002")!;
  camId = byMember.get("MES-003")!;
  evanId = byMember.get("MES-005")!;

  const combinedDrivers = await prisma.driver.findMany({
    where: { memberNum: { in: ["CMB-001", "CMB-002", "CMB-004"] } },
  });
  const byCombinedMember = new Map(combinedDrivers.map((d) => [d.memberNum!, d.id]));
  quinnId = byCombinedMember.get("CMB-001")!;
  raeId = byCombinedMember.get("CMB-002")!;
  leoId = byCombinedMember.get("CMB-004")!;
});

afterAll(async () => {
  await prisma.$disconnect();
  rmSync(TEST_DB_PATH, { force: true });
});

// ---------------------------------------------------------------------------
// Helper to build EntryForHistory-shaped objects for the pure-function tests.
// ---------------------------------------------------------------------------
function entry(
  paxIndex: number,
  runs: Array<{
    rawTimeMs: number | null;
    cones?: number;
    disposition?: "CLEAN" | "DNF" | "RRN" | "OFF" | "DSQ";
  }>,
  bestCommittedRunNumber: number | null = null,
): EntryForHistory {
  return {
    id: 1,
    driverId: 1,
    carNumber: "1",
    bestCommittedRunNumber,
    class: { code: "C1" },
    paxClass: { code: "C1", paxIndex: { toString: () => String(paxIndex) } },
    runs: runs.map((r, i) => ({
      runNumber: i + 1,
      rawTimeMs: r.rawTimeMs,
      cones: r.cones ?? 0,
      disposition: r.disposition ?? "CLEAN",
    })),
  };
}

describe("bestPaxMsForEntry", () => {
  it("returns nulls when no CLEAN runs exist", () => {
    const result = bestPaxMsForEntry(
      entry(1.0, [
        { rawTimeMs: 50000, disposition: "DNF" },
        { rawTimeMs: 51000, disposition: "RRN" },
      ]),
    );
    expect(result).toEqual({ bestRawMs: null, bestPaxMs: null });
  });

  it("filters out non-CLEAN runs and picks min of remaining", () => {
    const result = bestPaxMsForEntry(
      entry(1.0, [
        { rawTimeMs: 52000, disposition: "CLEAN" },
        { rawTimeMs: 49000, disposition: "DNF" }, // fastest but DNF → excluded
        { rawTimeMs: 50500, disposition: "RRN" }, // also excluded
        { rawTimeMs: 51000, disposition: "CLEAN" },
      ]),
    );
    expect(result.bestRawMs).toBe(51000);
    expect(result.bestPaxMs).toBe(51000);
  });

  it("applies cone penalty before taking min", () => {
    // 50000 + 1*2000 cone = 52000; vs 51500 clean → 51500 wins
    const result = bestPaxMsForEntry(
      entry(1.0, [
        { rawTimeMs: 50000, cones: 1 },
        { rawTimeMs: 51500, cones: 0 },
      ]),
    );
    expect(result.bestRawMs).toBe(51500);
  });

  it("uses cone-corrected time when cones make a run still the fastest", () => {
    // 50000 + 1*2000 = 52000; vs 53000 clean → 52000 wins
    const result = bestPaxMsForEntry(
      entry(1.0, [
        { rawTimeMs: 50000, cones: 1 },
        { rawTimeMs: 53000, cones: 0 },
      ]),
    );
    expect(result.bestRawMs).toBe(52000);
  });

  it("applies pax multiplier and rounds", () => {
    const result = bestPaxMsForEntry(
      entry(0.92, [{ rawTimeMs: 50000 }]),
    );
    expect(result.bestRawMs).toBe(50000);
    expect(result.bestPaxMs).toBe(46000); // round(50000 * 0.92)
  });

  it("returns nulls when CLEAN runs exist but rawTimeMs is null", () => {
    const result = bestPaxMsForEntry(
      entry(1.0, [{ rawTimeMs: null, disposition: "CLEAN" }]),
    );
    expect(result).toEqual({ bestRawMs: null, bestPaxMs: null });
  });

  it("honors bestCommittedRunNumber over the fastest CLEAN run", () => {
    // R1=58436ms (committed), R2=57534ms (faster clean) — mirrors Ellen G. at 2025-08-16.
    // bestCommittedRunNumber=1 → should use R1 (58436ms), not R2 (57534ms).
    const result = bestPaxMsForEntry(
      entry(
        1.0,
        [
          { rawTimeMs: 58436, cones: 0 }, // R1: committed best (slower)
          { rawTimeMs: 57534, cones: 0 }, // R2: faster clean (should be ignored)
        ],
        1, // bestCommittedRunNumber = 1 (R1)
      ),
    );
    expect(result.bestRawMs).toBe(58436);
    expect(result.bestPaxMs).toBe(58436);
  });

  it("falls back to fastest CLEAN when bestCommittedRunNumber is null", () => {
    const result = bestPaxMsForEntry(
      entry(
        1.0,
        [
          { rawTimeMs: 58436, cones: 0 },
          { rawTimeMs: 57534, cones: 0 },
        ],
        null, // no committed pointer → fallback
      ),
    );
    expect(result.bestRawMs).toBe(57534);
  });

  it("falls back to fastest CLEAN when committed run has null rawTimeMs", () => {
    // bestCommittedRunNumber points to a DNF (null rawTimeMs) → fall through to CLEAN
    const result = bestPaxMsForEntry(
      entry(
        1.0,
        [
          { rawTimeMs: null, disposition: "DNF" }, // R1: committed but DNF
          { rawTimeMs: 57534, cones: 0 },           // R2: fastest CLEAN
        ],
        1, // committed = R1 (DNF, null rawTimeMs)
      ),
    );
    expect(result.bestRawMs).toBe(57534);
  });
});

// ---------------------------------------------------------------------------
// Fixture overview (see build-multi-event-season.mjs header for full math):
//
//  Event 1 (2026-03-01) — 5 entrants
//    Pooled PAX:  Alex 50000, Cam(CS) 52440, Bea 55000, Dee 60000, Evan 62000
//  Event 2 (2026-04-05) — 4 entrants
//    Pooled PAX:  Alex 51000, Bea 53000, Cam(CS) 53360, Dee 56000
//  Event 3 (2026-05-10) — 4 entrants
//    Pooled PAX:  Alex 52000, Bea 54000, Cam(CS) 54280, Dee(CS) 56120
//  Event 4 (2026-06-14) — 3 entrants
//    Pooled PAX:  Alex 53000, Bea 57000, Dee(CS) 57040
//  Event 5 (2026-07-19) — 3 entrants, Cam DNF
//    Pooled PAX:  Bea(CS) 55200, Alex (54000+1cone)*1.0 = 56000.  Cam excluded.
// ---------------------------------------------------------------------------

describe("buildDriverHistory", () => {
  it("returns events in strict chronological order", async () => {
    const history = await buildDriverHistory(alexId, prisma);
    expect(history).toHaveLength(5);
    for (let i = 1; i < history.length; i++) {
      expect(history[i]!.eventDate.getTime()).toBeGreaterThan(
        history[i - 1]!.eventDate.getTime(),
      );
    }
  });

  it("omits events where the driver had no entry (Cam absent from event 4)", async () => {
    const history = await buildDriverHistory(camId, prisma);
    const eventNames = history.map((h) => h.eventName);
    expect(eventNames).toEqual([
      "Season Event 1",
      "Season Event 2",
      "Season Event 3",
      "Season Event 5",
    ]);
    expect(eventNames).not.toContain("Season Event 4");
  });

  it("computes Alex's per-event best, position, and leader delta", async () => {
    const history = await buildDriverHistory(alexId, prisma);

    // Event 1: Alex is pooled leader → pos=1, delta=0
    // 7 entrants: Alex(C1), Cam(CS), Gina(CS), Bea(C1), Fred(CS), Dee(C1), Evan(C1)
    expect(history[0]!.bestRawMs).toBe(50000);
    expect(history[0]!.bestPaxMs).toBe(50000);
    expect(history[0]!.leaderPaxMs).toBe(50000);
    expect(history[0]!.position).toBe(1);
    expect(history[0]!.entrantCount).toBe(7);
    expect(history[0]!.diffFromLeaderPct).toBe(0);

    // Events 2-4: Alex remains pooled PAX leader
    for (const idx of [1, 2, 3]) {
      expect(history[idx]!.position).toBe(1);
      expect(history[idx]!.diffFromLeaderPct).toBe(0);
    }

    // Event 5: Bea (CS) is PAX-faster, so Alex is pos=2.
    // Alex raw = 54000 + 1*2000 = 56000; Bea PAX = round(60000 * 0.92) = 55200.
    // 4 valid entrants: Bea=55200, Alex=56000, Fred=60720, Gina=74520.
    expect(history[4]!.bestRawMs).toBe(56000);
    expect(history[4]!.bestPaxMs).toBe(56000);
    expect(history[4]!.leaderPaxMs).toBe(55200);
    expect(history[4]!.position).toBe(2);
    expect(history[4]!.entrantCount).toBe(4);
    expect(history[4]!.diffFromLeaderPct).toBeCloseTo((56000 - 55200) / 55200, 6);
  });

  it("computes Bea's leader-delta at event 1", async () => {
    const history = await buildDriverHistory(beaId, prisma);
    const e1 = history.find((h) => h.eventName === "Season Event 1")!;
    // PAX order at event 1: Alex=50000(1), Cam=52440(2), Gina=53360(3), Bea=55000(4), ...
    // Adding Fred and Gina to event 1 pushes Bea from pos=3 to pos=4.
    expect(e1.bestPaxMs).toBe(55000);
    expect(e1.leaderPaxMs).toBe(50000);
    expect(e1.diffFromLeaderPct).toBeCloseTo(0.1, 6); // (55000-50000)/50000
    expect(e1.position).toBe(4);
    expect(e1.entrantCount).toBe(7);
  });

  it("renders Cam's DNF-only event 5 with nulls but still includes the row", async () => {
    const history = await buildDriverHistory(camId, prisma);
    const e5 = history.find((h) => h.eventName === "Season Event 5")!;
    expect(e5).toBeDefined();
    expect(e5.bestRawMs).toBeNull();
    expect(e5.bestPaxMs).toBeNull();
    expect(e5.position).toBeNull();
    expect(e5.percentile).toBeNull();
    expect(e5.diffFromLeaderPct).toBeNull();
    expect(e5.diffFromMedianPct).toBeNull();
    // Leader/median computed from the other entrants; entrantCount excludes Cam (DNF).
    // Event 5 now has 4 valid entrants: Bea(CS,55200), Alex(C1,56000), Fred(CS,60720), Gina(CS,74520).
    expect(e5.leaderPaxMs).toBe(55200);
    expect(e5.entrantCount).toBe(4);
    // Display fields still populated from Cam's CS entry.
    expect(e5.classCode).toBe("CS");
    expect(e5.paxClassCode).toBe("CS");
    expect(e5.carNumber).toBe("103");
  });

  it("computes entrantCount and percentile correctly", async () => {
    const history = await buildDriverHistory(evanId, prisma);
    // Evan only attended event 1 (7 entrants: original 5 + Fred + Gina), placed 7th (slowest PAX).
    expect(history).toHaveLength(1);
    expect(history[0]!.entrantCount).toBe(7);
    expect(history[0]!.position).toBe(7);
    expect(history[0]!.percentile).toBe(1); // 7/7 = 1 (last place)
  });

  it("computes median PAX correctly at event 1 (odd count)", async () => {
    // Sorted PAX at event 1: [50000, 52440, 55000, 60000, 62000] → median = 55000 (Bea).
    const history = await buildDriverHistory(beaId, prisma);
    const e1 = history.find((h) => h.eventName === "Season Event 1")!;
    expect(e1.medianPaxMs).toBe(55000);
    expect(e1.diffFromMedianPct).toBe(0); // Bea IS the median
  });

  it("computes median PAX correctly at event 5 (even count)", async () => {
    // Sorted PAX at event 5: [Bea=55200, Alex=56000, Fred=60720, Gina=74520]
    // Even count (4): median = round((56000 + 60720) / 2) = 58360.
    const history = await buildDriverHistory(alexId, prisma);
    const e5 = history.find((h) => h.eventName === "Season Event 5")!;
    expect(e5.medianPaxMs).toBe(58360);
    expect(e5.diffFromMedianPct).toBeCloseTo((56000 - 58360) / 58360, 6);
  });

  it("returns [] for a driver with no entries", async () => {
    const history = await buildDriverHistory(999_999, prisma);
    expect(history).toEqual([]);
  });
});

// ---------------------------------------------------------------------------
// M1.17 — combined (same-date, multi-session) event collapsing.
//
// Group 3 "Cone in 60 Seconds (A)"/"(B)" (2027-05-15), pooled-PAX-summed
// qualifiers (see build-combined-event-season.mjs header for full math):
//   Ivy   83000 (1st, leader)   Rae  86000 (2nd)   Quinn 88000 (3rd, median)
//   Owen 102120 (4th)          Pia 105800 (5th)
// Leo/Mia/Nick forfeit (missing a session, or class mismatch) and are
// excluded from the ranked pool. Quinn and Rae also raced the two earlier,
// non-combined groups (Spring Opener, Summer Classic) unchanged.
// ---------------------------------------------------------------------------
describe("buildDriverHistory — combined events (M1.17)", () => {
  it("collapses a same-date session pair into one combined row, pooled-PAX ranked", async () => {
    const history = await buildDriverHistory(quinnId, prisma);

    // 4 underlying Event rows (opener, classic, session A, session B)
    // collapse to 3 history rows.
    expect(history).toHaveLength(3);

    const single = history.filter((h) => !h.combined);
    expect(single.map((h) => h.eventName)).toEqual([
      "Spring Opener",
      "Summer Classic",
    ]);
    expect(single.every((h) => h.href === `/events/${h.eventSlug}`)).toBe(true);

    const combined = history.find((h) => h.combined);
    expect(combined).toBeDefined();
    expect(combined!.eventName).toBe("Cone in 60 Seconds");
    expect(combined!.href).toBe("/events/combined/2027-05-15");
    expect(combined!.bestRawMs).toBe(88000); // 38000 + 50000, C1 unpaxed
    expect(combined!.bestPaxMs).toBe(88000);
    expect(combined!.entrantCount).toBe(5); // Ivy, Rae, Quinn, Owen, Pia qualify
    expect(combined!.leaderPaxMs).toBe(83000); // Ivy
    expect(combined!.position).toBe(3);
    expect(combined!.percentile).toBeCloseTo(0.6, 6);
    expect(combined!.medianPaxMs).toBe(88000); // odd count (5) — Quinn IS the median
    expect(combined!.diffFromLeaderPct).toBeCloseTo((88000 - 83000) / 83000, 6);
    expect(combined!.diffFromMedianPct).toBe(0);
  });

  it("ranks a second qualifier in the same combined group correctly", async () => {
    const history = await buildDriverHistory(raeId, prisma);
    const combined = history.find((h) => h.combined);
    expect(combined).toBeDefined();
    expect(combined!.bestRawMs).toBe(86000); // 50000 + 36000
    expect(combined!.bestPaxMs).toBe(86000);
    expect(combined!.position).toBe(2);
    expect(combined!.percentile).toBeCloseTo(0.4, 6);
    expect(combined!.entrantCount).toBe(5);
    expect(combined!.leaderPaxMs).toBe(83000);
    expect(combined!.diffFromMedianPct).toBeCloseTo((86000 - 88000) / 88000, 6);
  });

  it("keeps a forfeited combined row (driver missing one session) with null position/percentile", async () => {
    // Leo only entered session A of the pair (no entry at all in session B) —
    // forfeits the ranked pool but the row is still rendered, like today's
    // DNF-only single-event rows.
    const history = await buildDriverHistory(leoId, prisma);
    expect(history).toHaveLength(1);
    const row = history[0]!;

    expect(row.combined).toBe(true);
    expect(row.eventName).toBe("Cone in 60 Seconds");
    expect(row.href).toBe("/events/combined/2027-05-15");
    expect(row.position).toBeNull();
    expect(row.percentile).toBeNull();
    expect(row.bestPaxMs).toBeNull();
    expect(row.bestRawMs).toBeNull();
    expect(row.diffFromLeaderPct).toBeNull();
    expect(row.diffFromMedianPct).toBeNull();

    // Display fields still populated from Leo's session-A entry.
    expect(row.classCode).toBe("C1");
    expect(row.carNumber).toBe("204");

    // Leader/median/entrantCount reflect the 5 qualifiers, unaffected by
    // Leo's own forfeit.
    expect(row.leaderPaxMs).toBe(83000);
    expect(row.entrantCount).toBe(5);
  });
});
